2025-04-16 06:20:11,291 - 16 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2025-04-16 06:20:11,299 - 16 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2025-04-16 06:20:11,647 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2025-04-16 06:20:11,860 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2025-04-16 06:20:11,971 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for MELANIA-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:11,978 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for MELANIA-USDT. Check network connection.
2025-04-16 06:20:11,980 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for REZ-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'REZ-USDT'
2025-04-16 06:20:11,980 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for REZ-USDT. Check network connection.
2025-04-16 06:20:11,985 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for TST-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'TST-USDT'
2025-04-16 06:20:11,986 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for TST-USDT. Check network connection.
2025-04-16 06:20:11,991 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_user_stream_data_source.HyperliquidPerpetualUserStreamDataSource - INFO - Subscribed to private order and trades changes channels...
2025-04-16 06:20:12,017 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:12,017 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:12,020 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for WCT-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:12,020 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for WCT-USDT. Check network connection.
2025-04-16 06:20:12,096 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for GMX-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'GMX-USDT'
2025-04-16 06:20:12,096 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for GMX-USDT. Check network connection.
2025-04-16 06:20:12,185 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:12,185 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:12,188 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for MANTA-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MANTA-USDT'
2025-04-16 06:20:12,188 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for MANTA-USDT. Check network connection.
2025-04-16 06:20:12,308 - 16 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for MELANIA-USDT. 1/6 completed.
2025-04-16 06:20:12,393 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_user_stream_data_source.BinancePerpetualUserStreamDataSource - INFO - Successfully obtained listen key YsUY7AVObyqb6xzKfLp5nXcdW17kIwsuny67ZlfUbm43IXCS14Mxrw9L7ZQvouUZ
2025-04-16 06:20:12,498 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for MELANIA-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:12,499 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for MELANIA-USDT. Check network connection.
2025-04-16 06:20:12,499 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for REZ-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'REZ-USDT'
2025-04-16 06:20:12,500 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for REZ-USDT. Check network connection.
2025-04-16 06:20:12,500 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for TST-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'TST-USDT'
2025-04-16 06:20:12,500 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for TST-USDT. Check network connection.
2025-04-16 06:20:12,500 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for WCT-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:12,501 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for WCT-USDT. Check network connection.
2025-04-16 06:20:12,501 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for GMX-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'GMX-USDT'
2025-04-16 06:20:12,501 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for GMX-USDT. Check network connection.
2025-04-16 06:20:12,501 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for MANTA-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 797, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MANTA-USDT'
2025-04-16 06:20:12,502 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Could not fetch last fee payment for MANTA-USDT. Check network connection.
2025-04-16 06:20:12,502 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for WCT-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 777, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:12,503 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Could not fetch last fee payment for WCT-USDT. Check network connection.
2025-04-16 06:20:12,714 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:12,715 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:13,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:13,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:13,082 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:13,167 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for WCT-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 403, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 777, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:13,168 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Could not fetch last fee payment for WCT-USDT. Check network connection.
2025-04-16 06:20:13,384 - 16 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for REZ-USDT. 2/6 completed.
2025-04-16 06:20:13,467 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:13,467 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:14,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:14,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:14,354 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:14,355 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:14,566 - 16 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for TST-USDT. 3/6 completed.
2025-04-16 06:20:14,812 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:14,812 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:15,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:15,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:15,806 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:15,806 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:16,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:16,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:16,244 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:16,246 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:17,089 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:17,089 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:17,469 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:17,470 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:17,576 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:17,577 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:18,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:18,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:18,392 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:18,798 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:18,798 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:19,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:19,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:19,198 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:19,199 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:20,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:20,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:20,139 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:20,139 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:20,670 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:20,670 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:21,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:21,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:21,620 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:21,620 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:22,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:22,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:22,247 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:22,247 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:22,840 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:22,840 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:23,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:23,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:23,624 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:23,624 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:23,714 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:24,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:24,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:24,120 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:24,121 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:25,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:25,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:25,168 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:25,169 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:25,414 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:25,414 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:26,105 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:26,105 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:26,627 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:26,627 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:26,924 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:26,925 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:27,027 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:27,027 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:27,847 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:27,847 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:28,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:28,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:28,434 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:28,435 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:28,953 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:29,084 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:29,085 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:29,085 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:29,086 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:29,883 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:29,883 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:30,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:30,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:30,348 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:30,348 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:31,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:31,005 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:31,366 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:31,367 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:31,633 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:31,633 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:32,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:32,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:32,773 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:32,774 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:32,877 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:32,877 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:33,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:33,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:34,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:34,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:34,107 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:34,107 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:34,258 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:34,258 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:34,259 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:35,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:35,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:35,346 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:35,347 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:35,695 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:35,696 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:36,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:36,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:36,563 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:36,563 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:37,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:37,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:37,125 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:37,125 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:37,780 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:37,781 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:38,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:38,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:38,733 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:38,734 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:39,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:39,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:39,077 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:39,078 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:39,515 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:40,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:40,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:40,135 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:40,136 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:40,362 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:40,363 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:41,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:41,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:41,572 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:41,572 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:41,618 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:41,619 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:42,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:42,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:42,848 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:42,848 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:42,962 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:42,962 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:43,009 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:43,010 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:44,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:44,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:44,088 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:44,089 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:44,443 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:44,443 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:44,748 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:45,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:45,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:45,403 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:45,403 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:45,979 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:45,979 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:46,038 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:46,038 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:46,883 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:46,883 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:47,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:47,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:47,383 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:47,384 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:48,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:48,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:48,294 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:48,294 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:48,799 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:48,800 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:49,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:49,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:49,552 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:49,553 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:49,990 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:50,073 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:50,073 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:50,235 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:50,235 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:50,798 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:50,798 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:51,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:51,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:51,706 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:51,706 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:52,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:52,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:52,248 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:52,248 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:53,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:53,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:53,134 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:53,134 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:53,513 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:53,513 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:54,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:54,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:54,500 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:54,500 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:54,780 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:54,780 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:55,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:55,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:55,254 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:55,946 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:55,946 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:56,005 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:56,006 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:56,008 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:56,009 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:57,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:57,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:57,312 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:57,312 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:57,366 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:57,367 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:58,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:58,002 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:20:58,633 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:20:58,634 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:20:58,790 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:58,790 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:20:59,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:20:59,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:21:00,000 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:21:00,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:21:00,188 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:21:00,189 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:21:00,326 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:21:00,327 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:21:00,578 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred fetching orderbook snapshots. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 168, in listen_for_order_book_snapshots
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 77, in _order_book_snapshot
    snapshot_response: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 64, in _request_order_book_snapshot
    ex_trading_pair = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:21:01,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:21:01,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:21:01,625 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:21:01,625 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:21:01,764 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:21:01,765 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:21:02,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:21:02,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:21:03,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - hyperliquid_perpetual_testnet is not ready. Please wait...
2025-04-16 06:21:03,001 - 16 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2025-04-16 06:21:03,283 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:21:03,283 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:21:03,426 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:21:03,426 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:21:03,658 - 16 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2025-04-16 06:21:04,708 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book data streams.
2025-04-16 06:21:04,709 - 16 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 125, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'MELANIA-USDT'
2025-04-16 06:21:04,787 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:21:04,787 - 16 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 108, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'WCT-USDT'
2025-04-16 06:21:06,680 - 16 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
